name: Go
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build Dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y cmake libtool libc6-dev
          cd /tmp
          git clone https://github.com/lzfse/lzfse.git
          cd lzfse
          mkdir build
          cd build
          cmake ..
          sudo make install
      - name: Build Dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install lzfse
      # - name: Build Dependencies (Windows)
      #   if: matrix.platform == 'windows-latest'
      #   run: |
      #     git clone https://github.com/lzfse/lzfse.git
      #     cd lzfse
      #     mkdir build
      #     cd build
      #     cmake -G "Visual Studio 16 2019" ..
      #     cmake --build . --config Debug
      #     cd Debug
      #     dlltool --def D:\a\ipsw\ipsw\hack\windows\lzfse.def --dllname lzfse.dll --output-lib lzfse.a

      - name: Get dependencies
        run: |
          go mod download

      - name: Build (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
          CGO_ENABLED=1 go build -o build/dist/ipsw -ldflags "-s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion="v1.0.0" -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime==$(date -u +%Y%m%d)" ./cmd/ipsw
      - name: Build (macOS)
        if: matrix.platform == 'macos-latest'
        run: sudo CGO_ENABLED=1 go build -o build/dist/ipsw -ldflags "-s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion="v1.0.0" -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime==$(date -u +%Y%m%d)" ./cmd/ipsw
      - name: Build (Windows)
        if: matrix.platform == 'windows-latest'
        env:
          CGO_LDFLAGS: -LD:\a\ipsw\ipsw\lzfse\build\Debug
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          go build -o build/dist/ipsw.exe -ldflags "-linkmode external -extldflags -static" ./cmd/ipsw
          dir build/dist
          dir

      # - name: Run Help
      #   if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
      #   run: LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw --help
      # - name: Run Help (Windows)
      #   if: matrix.platform == 'windows-latest'
      #   run: D:\a\ipsw\ipsw\build\dist\ipsw.exe --help

      - name: Run Device List
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw device-list
      - name: Run Device List (Windows)
        if: matrix.platform == 'windows-latest'
        run: D:\a\ipsw\ipsw\build\dist\ipsw.exe device-list

      - id: get-latest
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: |
          echo ::set-output name=version::$(LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw download latest --info)

      - name: Run Extract Remote Kernelcache
        if: matrix.platform == 'ubuntu-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw -V download kernel -v 14.6 -d iPhone12,1
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw -V macho */kernelcache*

      - name: Run Extract Remote Kernelcache (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          D:\a\ipsw\ipsw\build\dist\ipsw.exe -V download kernel -v 14.6 -d iPhone12,1
          dir

      - name: Run Extract ALL Remote Kernelcaches
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw download kernel -v 14.6 -d iPhone12,1
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw -V macho */kernelcache*

      # - name: Run ipsw update
      #   if: matrix.platform == 'macos-latest'
      #   run: |
      #     build/dist/ipsw update --platform windows_x86_64 -V
      #     build/dist/ipsw update --detect

      - uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: build/dist/
